[versions]
kotlin = "1.8.22"
paper = "1.20.1-R0.1-SNAPSHOT"
paper-api = "1.20"

[libraries]
paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
